package com.eurekaconsumer.pojo;

import java.io.Serializable;

public class GradeInfo implements Serializable {
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String campus;
    private String faculty;
    private String major;
    private String grade;
    private Integer sum;
    private Integer stuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public GradeInfo(Integer id, String campus, String faculty, String major, String grade, Integer sum, Integer stuId) {
        this.id = id;
        this.campus = campus;
        this.faculty = faculty;
        this.major = major;
        this.grade = grade;
        this.sum = sum;
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public GradeInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.campus
     *
     * @return the value of grade.campus
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public String getCampus() {
        return campus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.campus
     *
     * @param campus the value for grade.campus
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public void setCampus(String campus) {
        this.campus = campus == null ? null : campus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.faculty
     *
     * @return the value of grade.faculty
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public String getFaculty() {
        return faculty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.faculty
     *
     * @param faculty the value for grade.faculty
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public void setFaculty(String faculty) {
        this.faculty = faculty == null ? null : faculty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.major
     *
     * @return the value of grade.major
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.major
     *
     * @param major the value for grade.major
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade
     *
     * @return the value of grade.grade
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade
     *
     * @param grade the value for grade.grade
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.sum
     *
     * @return the value of grade.sum
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.sum
     *
     * @param sum the value for grade.sum
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.stu_id
     *
     * @return the value of grade.stu_id
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.stu_id
     *
     * @param stuId the value for grade.stu_id
     *
     * @mbggenerated Mon May 29 19:33:34 CST 2023
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }
}